<?php

namespace common\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use frontend\components\Common;

/**
 * This is the model class for table "advert".
 *
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $price
 * @property string $address
 * @property string $location
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $general_image
 * @property string $category
 * @property string $agent_contact
 * @property integer $views
 */
class Advert extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }


    public function scenarios(){
        $scenarios = parent::scenarios();
        $scenarios['step2'] = ['general_image'];

        return $scenarios;
    }

    public static function tableName()
    {
        return 'advert';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'description', 'price', 'address', 'location', 'category', ], 'required'],
            [['description'], 'string'],
            [['created_at', 'updated_at'], 'integer'],
            [['title', 'category'], 'string', 'max' => 100],
            [['price'], 'string', 'max' => 15],
            [['address', 'general_image'], 'string', 'max' => 255],
            [['location', 'agent_contact'], 'string', 'max' => 60],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'description' => 'Description',
            'price' => 'Price',
            'address' => 'Address',
            'location' => 'Location',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'general_image' => 'General Image',
            'category' => 'Category',
            'agent_contact' => 'Agent Contact',
            'comments' =>'Comments',
            'views' => 'Views',
        ];
    }

    public function getUser()
    {

        return $this->hasOne(User::className(), ['id' =>'agent_contact']);
    }




    public static function find()
    {
        return new AdvertQuery(get_called_class());
    }



    public function afterValidate()
    {
        parent::afterValidate(); // TODO: Change the autogenerated stub

        $this->agent_contact= Yii::$app->user->identity->id;


    }


    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        Yii::$app->locator->cache->set('id',$this->id);
    }


    public function getTitle(){

        return Common::getTitleAdvert($this);
    }




}
